trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
      - "**/*.md"

pr:
  - master

variables:
  - template: .azure-variables-template.yml

stages:
  - stage: Build
    displayName: 🚧 Build
    jobs:
      - job: Build
        displayName: Build with .NET Core SDK
        pool:
          vmImage: ubuntu-18.04
        steps:

          - task: UseDotNet@2
            displayName: Install .NET Core 3.1 SDK
            inputs:
              version: $(sdkVersion)
              packageType: sdk

          - script: dotnet help
            displayName: Initialize .NET Core environment

          - task: DotNetCoreCLI@2
            displayName: Build project with release version
            inputs:
              command: build
              projects: $(projectPath)
              arguments: >
                --configuration $(buildConfiguration)

          # DotNetCoreCLI@2 with pack ignores arguments input, resorting to bash here.
          # TODO replace with DotNetCoreCLI task when it's fixed
          # Quotes around output path are needed so backslashes aren't interpreted
          # as escape symbols effectively cutting them out.
          - bash: >
              dotnet pack
              --no-build
              --output "$(Build.ArtifactStagingDirectory)/packages/release"
              --configuration $(buildConfiguration)
              $(projectPath)
            displayName: Create release nuget package

          - task: DotNetCoreCLI@2
            displayName: Build project with CI version
            inputs:
              command: build
              projects: $(projectPath)
              arguments: >
                --configuration $(buildConfiguration)
                --version-suffix "$(ciVersionSuffix)"

          # DotNetCoreCLI@2 with pack ignores arguments input, resorting to bash here.
          # TODO replace with DotNetCoreCLI task when it's fixed
          # Quotes around output path are needed so backslashes aren't interpreted
          # as escape symbols effectively cutting them out.
          - bash: >
              dotnet pack
              --no-build
              --output "$(Build.ArtifactStagingDirectory)/packages/ci"
              --configuration $(buildConfiguration)
              --version-suffix "$(ciVersionSuffix)"
              $(projectPath)
            displayName: Create CI nuget package

          - publish: $(Build.ArtifactStagingDirectory)/packages
            artifact: packages

  - stage: PublishArtifacts
    dependsOn: Build
    displayName: 📤 Publish artifacts
    # publish artifacts only for pull requests that is coming from the same repo
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], False))
    jobs:
      - job: PublishArtifacts
        displayName: Publish artifacts
        pool:
          vmImage: ubuntu-18.04
        steps:

          - checkout: none

          - download: current
            artifact: packages
            # quotes are needed since * can't be used as the first character without quotes
            patterns: "*/**/*.*upkg"

          - task: UseDotNet@2
            displayName: Install .NET Core 3.1 SDK
            inputs:
              version: $(sdkVersion)
              packageType: sdk

          - script: dotnet help
            displayName: Initialize .NET Core environment

          - task: DotNetCoreCLI@2
            displayName: Publish CI package to Azure artifacts
            inputs:
              command: push
              nuGetFeedType: internal
              feedPublish: $(internalFeedName)
              publishPackageMetadata: true
              packagesToPush: $(Pipeline.Workspace)/packages/ci/*.*upkg

  - stage: UnitTest
    dependsOn: PublishArtifacts
    displayName: 🧪 Unit test
    condition: succeeded()
    jobs:
      - job: UnitTest
        displayName: Run unit tests
        pool:
          vmImage: ubuntu-18.04
        steps:

          - task: UseDotNet@2
            displayName: Install .NET Core 3.1 SDK
            inputs:
              version: $(sdkVersion)
              packageType: sdk

          - script: dotnet help
            displayName: Initialize .NET Core environment

          - task: DotNetCoreCLI@2
            displayName: Execute unit tests
            inputs:
              command: test
              projects: $(unitTestsPackage)
              configuration: $(buildConfiguration)
              arguments: >
                --verbosity normal
              publishTestResults: true

  - stage: Release
    displayName: 🚀 Release
    dependsOn: UnitTest
    # don't push release package on pull requests
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: Release
        displayName: Publish package to NuGet
        pool:
          vmImage: ubuntu-18.04
        steps:

          - checkout: none

          - download: current
            artifact: packages
            # don't remove quotes
            patterns: "*/**/*.*upkg"

          - task: UseDotNet@2
            displayName: Install .NET Core 3.1 SDK
            inputs:
              version: $(sdkVersion)
              packageType: sdk

          - script: dotnet help
            displayName: Initialize .NET Core environment

          - bash: >
              dotnet nuget push
              $(Pipeline.Workspace)/packages/release/*.nupkg
              --api-key $(NugetApiKey)
              --skip-duplicate
              --source https://nuget.org
            displayName: Publish package to NuGet

          - bash: >
              dotnet nuget push
              $(Pipeline.Workspace)/packages/release/*.snupkg
              --api-key $(NugetApiKey)
              --skip-duplicate
              --source https://nuget.org
            displayName: Publish symbols to NuGet
