variables:
  buildConfiguration: Release
  vm: ubuntu-18.04
  sdkVersion: 3.1.100
  projectPath: src/FooLib/FooLib.csproj
  internalFeedName: testrepo/FooLib
  ciVersionSuffix: ci.$(Build.BuildId)+git.commit.$(Build.SourceVersion)
  unitTestsPackage: test/FooLibTests/FooLibTests.csproj
  integrationTestsPackage: test/Integration/FooLibTests.Integration.csproj
