trigger:
  batch: true
  branches:
    include:
      - '*'

variables:
  buildConfiguration: Release

stages:
  - stage: Build
    displayName: 🚧
    jobs:
      - job: BuildOnWindows
        displayName: Build with .NET Core SDK on Windows
        pool:
          # windows image is used because it's the only way to use NugetCommand@2 with
          # support of ignoring publishing of packages with the same version
          vmImage: windows-2019
        steps:
          - task: UseDotNet@2
            displayName: Install .NET Core 3.1 SDK
            inputs:
              version: 3.1.100
              packageType: sdk
          - script: dotnet help
            displayName: Initialize .NET Core Environment
          - task: DotNetCoreCLI@2
            displayName: Build Package
            inputs:
              command: build
              projects: src/FooLib/FooLib.csproj
              arguments: >
                --configuration $(buildConfiguration)
                --version-suffix "ci.$(Build.BuildId)+git.commit.$(Build.SourceVersion)"
          # DotNetCoreCLI@2 with pack ignores arguments input, resorting to bash here.
          # Quotes around output path are needed so backslashes aren't interpreted
          # as escape symbols effectively cutting them out.
          - bash: >
              dotnet pack
              --output "$(Build.ArtifactStagingDirectory)\packages\release"
              --configuration $(buildConfiguration)
              src/FooLib/FooLib.csproj
            displayName: Pack Release Package
          # Currently creating a package with semver 2.0 gives a warning about older
          # clients, that's fine. It can't be disabled without disabling all package analysing
          # during pack so we can just ignore it.
#          - bash: >
#              dotnet pack
#              --output "$(Build.ArtifactStagingDirectory)\packages\ci"
#              --configuration $(buildConfiguration)
#              --version-suffix "ci.$(Build.BuildId)+git.commit.$(Build.SourceVersion)"
#              src/FooLib/FooLib.csproj
#            displayName: Pack CI Package
          - publish: $(Build.ArtifactStagingDirectory)/packages
            artifact: packages

  - stage: PublishArtifacts
    dependsOn: Build
    displayName: 📤
    condition: succeeded()
    jobs:
      - job: PublishArtifacts
        displayName: Publish Artifacts
        pool:
          vmImage: windows-2019
        steps:
          - checkout: none
          - download: current
            artifact: packages
            # quotes are needed since * can't be used as the first character without quotes
            patterns: '*/**/*.nupkg'
          - task: NuGetCommand@2
            displayName: Publish CI Package to Azure Artifacts
            inputs:
              command: push
              publishVstsFeed: testrepo/FooLib
              packagesToPush: "$(Pipeline.Workspace)/packages/ci/*.nupkg"
              allowPackageConflicts: true

  - stage: UnitTest
    dependsOn: PublishArtifacts
    displayName: 🧪
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: UnitTest
        displayName: Run Unit Tests
        strategy:
          matrix:
            Windows:
              VM_IMAGE: windows-2019
            Ubuntu:
              VM_IMAGE: ubuntu-18.04
            macOS:
              VM_IMAGE: macOS-10.14
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - task: UseDotNet@2
            displayName: Install .NET Core 3.1 SDK
            inputs:
              version: 3.1.100
              packageType: sdk
          - script: dotnet help
            displayName: Initialize .NET Core Environment
          - task: DotNetCoreCLI@2
            displayName: Execute Unit Tests
            inputs:
              command: test
              projects: test/FooLibTests/FooLibTests.csproj
              configuration: $(buildConfiguration)
              arguments: >
                --verbosity normal
              publishTestResults: true
              workingDirectory: $(Build.SourcesDirectory)

  - stage: Release
    displayName: 🚀
    dependsOn: UnitTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Release
        displayName: Publish Package to NuGet
        pool:
          vmImage: windows-2019
        steps:
          - checkout: none
          - download: packages
            # don't remove quotes
            patterns: "*/**/*.nupkg"
          - task: NuGetCommand@2
            displayName: Publish Package to NuGet
            inputs:
              command: push
              includeNugetOrg: true
              nuGetFeedType: external
              publishFeedCredentials: NuGet
              packagesToPush: '$(Pipeline.Workspace)/packages/release/*.nupkg'
              allowPackageConflicts: true
