trigger:
  batch: true
  branches:
    include:
      - 'master'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Install .NET Core 3.1 SDK"
  inputs:
    packageType: sdk
    version: 3.1.100
- task: DotNetCoreCLI@2
  displayName: "Build Package with CI version"
  inputs:
    command: build
    projects: src/FooLib/FooLib.csproj
    configuration: "Release"
    workingDirectory: $(Build.SourcesDirectory)
    arguments: --version-suffix 'ci-$(Build.BuildId)+$(Build.SourceVersion)'
    outputDir: '$(Build.ArtifactStagingDirectory)/packages/pipeline'
- task: NuGetCommand@2
  displayName: "Publish CI Package to Azure Artifacts"
  condition: succeeded()
  inputs:
    command: push
    publishVstsFeed: FooLib
    packagesToPush: src/**/*-ci-*.nupkg
- task: DotNetCoreCLI@2
  displayName: "List Unit Tests"
  inputs:
    command: test
    projects: test/FooLibTests/FooLibTests.csproj
    configuration: "Release"
    arguments: --list-tests test/FooLibTests/
    workingDirectory: $(Build.SourcesDirectory)
- task: DotNetCoreCLI@2
  displayName: "Execute Unit Tests"
  inputs:
    command: test
    projects: test/FooLibTests/FooLibTests.csproj
    configuration: "Release"
    arguments: >
      --no-build 
      --verbosity normal
    publishTestResults: true
    workingDirectory: $(Build.SourcesDirectory)
