trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
      - "**/*.md"

pr: none

variables:
  - template: variables.yml

stages:
  - stage: Build
    displayName: 🚧 Build
    jobs:
      - job: Build
        displayName: Build with .NET Core SDK
        pool:
          vmImage: $(vmImage)
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build project with release version
            inputs:
              command: build
              projects: $(projectPath)
              arguments: >
                --configuration $(buildConfiguration)

          - bash: >
              dotnet pack
              --no-build
              --output "$(Build.ArtifactStagingDirectory)/packages/release"
              --configuration $(buildConfiguration)
              $(projectPath)
            displayName: Create release nuget package

          - publish: $(Build.ArtifactStagingDirectory)/packages
            artifact: packages

  - stage: Release
    displayName: 🚀 Release
    dependsOn: UnitTest
    jobs:
      - job: Release
        displayName: Publish package to NuGet
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: none

          - download: current
            artifact: packages
            patterns: "*/**/*.*upkg"

          - bash: >
              dotnet nuget push
              $(Pipeline.Workspace)/packages/release/*.nupkg
              --api-key $(NugetApiKey)
              --skip-duplicate
              --source https://nuget.org
            displayName: Publish package to NuGet

          - bash: >
              dotnet nuget push
              $(Pipeline.Workspace)/packages/release/*.snupkg
              --api-key $(NugetApiKey)
              --skip-duplicate
              --source https://nuget.org
            displayName: Publish symbols to NuGet
