trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/
    - README.md

pr: none

variables:
- template: variables.yml

pool:
  vmImage: $(vmImage)

steps:
- task: DotNetCoreCLI@2
  displayName: Build project with release version
  inputs:
    command: build
    projects: $(projectPath)
    arguments: >
      --configuration $(buildConfiguration)
      -p:Version=$(releaseVersion)
- bash: >
    dotnet pack
    --no-build
    --output "$(Build.ArtifactStagingDirectory)/packages"
    --configuration $(buildConfiguration)
    -p:Version=$(releaseVersion)
    $(projectPath)
  displayName: Create release nuget package
- bash: >
    dotnet nuget push
    $(Build.ArtifactStagingDirectory)/packages/*.nupkg
    --api-key $(NugetApiKey)
    --skip-duplicate
    --source https://api.nuget.org/v3/index.json
  displayName: Publish package to NuGet
- task: GitHubRelease@0
  inputs:
    action: create
    target: $(Build.SourceVersion)
    tagSource: manual
    tag: v$(releaseVersion)
    tagPattern: v$(releaseVersion)
    title: $(releaseVersion)
    githubConnection: githubRelease
    repositoryName: $(Build.Repository.Name)
    isPreRelease: $(isPreRelease)
    addChangeLog: false
    assets: $(Build.ArtifactStagingDirectory)/packages/*
  displayName: Create Github Release
