trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/
      - README.md

pr: none

variables:
  - template: variables.yml

stages:
  - stage: Build
    displayName: 🚧 Build
    jobs:
      - job: Build
        displayName: Build with .NET Core SDK
        pool:
          vmImage: $(vmImage)
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build project with release version
            inputs:
              command: build
              projects: $(projectPath)
              arguments: >
                --configuration $(buildConfiguration)
                -p:Version=$(versionPrefix)

          - bash: >
              dotnet pack
              --no-build
              --output "$(Build.ArtifactStagingDirectory)/packages"
              --configuration $(buildConfiguration)
              -p:Version=$(versionPrefix)
              $(projectPath)
            displayName: Create release nuget package

          - publish: $(Build.ArtifactStagingDirectory)/packages
            artifact: packages

  - stage: Release
    displayName: 🚀 Release
    jobs:
      - job: Release
        displayName: Publish package to NuGet
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: none

          - download: current
            artifact: packages

          - bash: >
              dotnet nuget push
              $(Pipeline.Workspace)/packages/*.nupkg
              --api-key $(NugetApiKey)
              --skip-duplicate
              --source https://api.nuget.org/v3/index.json
            displayName: Publish package to NuGet

          - task: GitHubRelease@0
            inputs:
              action: create
              tagSource: auto
              tag: v$(versionPrefix)
              releaseTitle: $(versionPrefix)
              githubConnection: tuscen
              repositoryName: $(Build.Repository.Name)
              assets: $(Pipeline.Workspace)/packages/*
            displayName: Create Github Release
