trigger:
  batch: true
  branches:
    exclude:
      - master
      - gh-pages
  paths:
    exclude:
      - docs/
      - "*.md"

pr: none

variables:
  - template: variables.yml

stages:
  - stage: UnitTest
    displayName: 🧪 Unit test
    jobs:
      - template: jobs/run-unit-tests.yml
        parameters:
          buildConfiguration: $(buildConfiguration)
          projects: $(unitTestsProject)
          strategies:
            - Ubuntu: ubuntu-18.04
