variables:
  - group: Integration Tests Variables
  - name: versionPrefix
    value: 0.0.16
  - name: versionSuffix
    value: 'alpha.1'
  - name: ciVersionSuffix
    value: ci.$(Build.BuildId)+git.commit.$(Build.SourceVersion)
  - name: isPreRelease
    value: ${{ ne(variables.versionSuffix, '')) }}
  - name: releaseVersion
    ${{ if (isPreRelease) }}:
      value: $(versionPrefix)-$(versionSuffix)
    ${{ else }}:
      value: $(versionPrefix)
  - name: ciVersion
    value: $(releaseVersion).$(ciVersionSuffix)
  - name: buildConfiguration
    value: Release
  - name: vmImage
    value: ubuntu-20.04
  - name: projectPath
    value: src/FooLib/FooLib.csproj
  - name: internalFeedName
    value: testrepo/FooLib
  - name: unitTestsProject
    value: test/FooLibTests/FooLibTests.csproj
  - name: integrationTestsProject
    value: test/Integration/FooLibTests.Integration.csproj
