variables:
  buildConfiguration: Release
  vmImage: ubuntu-18.04
  sdkVersion: 3.1.100
  projectPath: src/FooLib/FooLib.csproj
  internalFeedName: testrepo/FooLib
  ciVersionSuffix: ci.$(Build.BuildId)+git.commit.$(Build.SourceVersion)
  unitTestsProject: test/FooLibTests/FooLibTests.csproj
  integrationTestsProject: test/Integration/FooLibTests.Integration.csproj
