variables:
  - group: Integration Tests Variables
  - name: buildConfiguration
    value: Release
  - name: vmImage
    value: ubuntu-18.04
  - name: projectPath
    value: src/FooLib/FooLib.csproj
  - name: internalFeedName
    value: testrepo/FooLib
  - name: versionPrefix
    value: 0.0.11
  - name: ciVersionSuffix
    value: ci.$(Build.BuildId)+git.commit.$(Build.SourceVersion)
  - name: unitTestsProject
    value: test/FooLibTests/FooLibTests.csproj
  - name: integrationTestsProject
    value: test/Integration/FooLibTests.Integration.csproj
